### ISSUE TITLE
Can't run the app

### ISSUE THREAD

**Issue by NiHuShu** [ExtraordinaryBen/DuinoBoX#1]
Is there any way to run windows app without downloading the whole QT?

**Comment by ExtraordinaryBen** [comment]
I will look into making sure all the required DLLs are included during the next binary release.
In the meantime, I do not recommend using this project. Something with the way the Arduino Uno behaves corrupts the first byte of the Xbox's EEPROM when attempting to read it. If you do not already have an EEPROM backup you risk corrupting your HDD key.

I recommend looking at PiPROM instead: https://github.com/grimdoomer/PiPROM

**Comment by NiHuShu** [comment]
Sadly I don't have a PI. Would it work on Arduino Leonardo because that's all I have

**Comment by ExtraordinaryBen** [comment]
I do not have an Arduino Leonardo to test, but even if it did there still would be the risk of corrupting your Xbox's EEPROM.

You can always build your own cable as well: https://www.instructables.com/id/XBox-EEPROM-ReaderWriter/

**Comment by dx4m** [comment]
The first byte gets only corrupted because you have an error in your code. The EEPROM has only 256 bytes in size so the address range is only from 0x00 to 0xFF and the xbox eeprom accepts only one address byte. Your code writes 2 bytes for the addresses which triggers an EEPROM write to address 0 with the data of the address you really want to dump. Look at my repo that I posted using an ESP8266 to dump the EEPROM.

**Comment by ExtraordinaryBen** [comment]
Well, I feel dumb...Haha! When I initially wrote the Arduino code, I was testing with an Atmel 24C256 EERPOM (256KBytes of storage.) Thus I had mistakenly left the extra write commands.

Thank you @dx4m for your help! I've been so busy with my new job that I completely forgot about coming back and working on this.

@NiHuShu I'll see if I have some time this weekend to test the fix and repackage the program with all the dependent DLLs for the Windows app.

**Comment by Traace** [comment]
Hey @ExtraordinaryBen thanks for your work.

I think getting a Arduino would be great to read out eeprom from my consoles. 

Seems like you fixed the dll and byte corrupt issue. Do you think its safe to use it now or better get a PI or serial cable?

**Comment by ExtraordinaryBen** [comment]
@Traace Oh, I forgot to close the issue didn't I? :stuck_out_tongue: 
I have tested the Arduino sketch and app on a v.1.0 xbox that had a dead HDD and recovered the EEPROM so I could construct a new drive. 

So yeah it's safe to use now. The app doesn't decrypt everything that's in the EEPROM just yet, but it will let you save the EEPROM as a .bin file to your computer.

Happy hacking!

**Comment by milanmaharaj** [comment]
i am trying so hard to use this to read an eeprom. i cant seem to get it working. i have uploaded the sketch and connected the sda and scl cables correctly. the programme returns GO when connected on the bottom the left and returns GO EEPROM NOT FOUND when the device isnt connected however it does not read the eeprom at all. both on charger and when connected to a pc. please help me i am losing my mind trying to make this work

**Comment by ExtraordinaryBen** [comment]
@milanmaharaj, please to not revive closed issues. Instead create a new issue with additional details. (Xbox revision, how you're trying to read the eeprom while the xbox is booting, etc.)
