### ISSUE TITLE
Duinobox help with arduino

### ISSUE THREAD

**Issue by John874** [ExtraordinaryBen/DuinoBoX#3]
I need help using duinobox. Im a noob and need help with wiring and using the code

**Comment by ExtraordinaryBen** [comment]
I will answer specific questions related to using DuinoBox, but I'm not going to do the research for you. Use a search engine to look up how to use an Arduino, and how to extract xbox EEPROMs in general.

There are plenty of guides on how to use an EEPROM reader for the xbox, such as this video: https://www.youtube.com/watch?v=uzrljlHDr9w
