### ISSUE TITLE
EEPROM repair after read

### ISSUE THREAD

**Issue by milanmaharaj** [ExtraordinaryBen/DuinoBoX#4]
I managed to use this project to read my eeprom successfully THANKS A MILLION!! (however HD information does not populate in liveinfo when its loaded) all another info is correct. It worked successfully to lock a new hard drive using xboxhdm. Now I put the new hard drive in and turned the console on and there is no av output, and the ring blinks and console Fan goes slower, xbox cycles power 2 or 3 times ( fan noise goes up and down and green light off and on ), then continues to flash red with fan on normal speed no flubber on the screen no error message etc. Basically no av. I have seen another person experiencing a similar issue of breaking their eeprom when using an arduino  to dump its contents. If this is the case I have noticed there is a bit of code within your sketch that is able to write an EEPROM to the xbox however I am unaware how to use it and declare the array that you use inside that function. Please can you tell me how I would go about doing this in order to put my eeprom.bin or another verified one back onto my chip most methods seem quite complex and the sketches available are mostly for other microcontrollers. I'm unsure how to pass the bin file into your programme or make it into an array that that be used by your write function. I'm using a 1.3 Pal Xbox classic which is totally bricked. I'm going to be in some big trouble if I cant get this right as the console is not mine. Neither is the arduino. Please can you help me. I have searched and seen that piprog is specifically designed to do this however I only have a clone arduino and very little time.

**Comment by ExtraordinaryBen** [comment]
If you're referring to my Arduino sketch, it shouldn't break the EEPROM anymore. I do not have the program or arduino sketch designed to write back to the xbox's EEPROM, as I did not want to deal with people coming to me if they accidentally ruin their consoles.

The HD information on liveinfo is for any IDE hard drive you may have connected to your PC. So it's normal on most modern PCs for it not to be populated.

Is the way it's behaving with the new hard drive the same as the old hard drive??? First thing I'd try is to boot up from the old drive again. If that works you'll know the EEPROM isn't corrupted on the xbox.  

It really sounds like you're rushing through things on another person's xbox without fully being experienced in this kind of thing. You shouldn't be doing these kind of favors for friends unless you've done this plenty of times and know how to troubleshoot and repair xbox consoles in general. This kind of stuff takes time to learn, you shouldn't be using a friend's console to learn on.

When you say "I'm using a 1.3 Pal Xbox classic which is totally bricked." Are you saying the old drive was dead, or it's behaving bricked with the new drive? If the old drive was already dead, why the rush then?

**Comment by milanmaharaj** [comment]
My friend you are somewhere far away on this planet but I want to thank you so much, I really appreciate your information and willingness to share. I have no idea which sketch worked at this point but I managed to get the console working perfectly. I used just the eeprom file generated by your sweet sweet code to fix my console I am unaware if it got patched up or completely replaced but the console came on and booted straight into the softmod I injected into the new 160gb ide hdd, again using the eeprom your code dumped to lock the HDD. Along the process of the softmod I noticed it backing up my eeprom so I will copy that copy soon just incase. The xbox is not mine it is my partners and she was about to kill me for toying with it. We are currently on lockdown here in south africa and she loves this console and the nostalgia it brings far more than my life. Thankfully it all worked out perfectly and I have made her smile. If you believe in good brings good you my friend should have a blessed life!! Thanks a million once again I wish I could somehow show you my gratitude !

**Comment by ExtraordinaryBen** [comment]
@milanmaharaj  Happy to hear you got it working and she's forgiven you for not breaking it! :smile:  Modding Xbox consoles can be a tricky business, but it sounds like you have the intelligence and ingenuity to work things out!

I hope you and your partner also have a most blessed life! Peace be with you my friend.

**Comment by milanmaharaj** [comment]
Just on a side note to clarify I completely bricked the original hard drive through xplorer360 trying the ndure 3.1 method of placing the files onto c and e. It worked in copying the folders from the drive using xplorer360 , then it seemed to work for copying back C after ndure 3.1 install on the folder, then it bombed out on E and that was the end. I switched the adapter of and back on and then Xplorer360 only saw 4 partions not 5. That was it. The drive never recovered. Xboxhdm did nothing besides browse the files a few times and tell me the lock status annoyingly accurately. The rebuild and fix c options failed on 2 adapters and 2 different IDE motherboards on all master/slave configs and many hours of restarting and booting. Went through hell trying to boot xboxhdm iso's or use the bat files from xboxhdm2.3 usb. Got stuck coz I dont have an IDE dvd drive for anything before 2.2. So 1.9 cd burns never worked out in terms of booting into linux and using xboxhdm. I even tried using the xbox disc drive to boot my first ever pc an old core 2 quad as this is one of the pc's with ide, didnt work. Hdd was completely stonewalled. Could find total clusters of 200005690 or something at start of rebuild option but then would not create partitions just hangs . Xboxhdm would not find partition table when trying to build c but would find it when browsing files. Copying files with browser would throwback no space left on drive but xboxhdm and xplorer360 would not see any files on the partitions. At this point the only thing I can do with it is see the lock status through xboxhdm. Oh and unlock it through hotswop. I havent tried unlocking it with the eeprom I dumped using duinobox but I'm sure it will work since that eeprom locked the drive the xbox is currently using without issues. After seeing the eeprom duinobox dumped showed accurate stuff( I checked the last 3 digits of the serial were the same on the sticker and on the screen) I darted of to build the 160gb I'm using now. After running I to problems with the adapter and locking I eventually used the core 2 quad to lock the drive. When I tried to use the new drive I discovered something broke my eeprom.

Also the programme kept returning "GO" and not dumping the eeprom since my power supply was fried , giving like 1.4V, so once that was fixed with a good 12V at 2A one the arduino dumped the eeprom perfectly. Although your programme didn't indicate success. Had it not been for my constantly saving and using liveinfo to check each dump I saved after each attempt i would not have known it worked. It kept returning arduino eeprom empty , even though it did dump the eeprom and subsequently saved it. The info did not populate either, not even once. Basically it was kinda really lucky that i had read a certain post of successfully dumping and using an eeprom even though the programme returned arduino eeprom empty this person said this eeprom worked in locking a new hdd so once i had that I on to making a new hdd. Once again thanks for everything you really saved my skin with this project.

**Comment by ExtraordinaryBen** [comment]
I've recently become aware from others as well that the program incorrectly reports that the "Arduino EEPROM is empty," even though it is capturing the EEPROM data. I will need to review and update the program's code to address this issue.
